module VagrantPlugins
  module DNS
    module Action
      # Create resolver files.
      class SetResolvers
        def initialize(app, env)
          @app = app
        end

        def call(env)
          # ~/.vagrant.d/tmp/dns/resolver
          tmp_dns_path    = File.join(env[:tmp_path], "dns")
          resolver_folder = File.join(tmp_dns_path, "resolver")

          # VagrantDNS::Config.listen.first.last
          # [[:udp, "127.0.0.1", 5300]]
          port = 5300

          # Config
          tlds = env[:machine].config.dns.tlds

          FileUtils.mkdir_p(resolver_folder)

          tlds.each do |tld|
            File.open(File.join(resolver_folder, tld), "w") do |f|
              f << resolver_file(port)
            end
          end

          env[:ui].info "Created resolvers"

          @app.call(env)
        end

        private

        def resolver_file(port)
          contents = <<-FILE
# this file is generated by vagrant-dns
nameserver 127.0.0.1
port #{port}
FILE
        end
      end
    end
  end
end
