module VagrantPlugins
  module DNS
    module Action
      # Create resolver files in ~/.vagrant.d/tmp/dns/resolver
      class CreateResolvers
        def initialize(app, env)
          @app = app
        end

        def call(env)
          tmp_dns_path    = env[:dns].tmp_path
          resolver_folder = File.join(tmp_dns_path, "resolver")

          port = VagrantPlugins::DNS.listen.first.last # 5300
          tlds = env[:machine].config.dns.tlds

          FileUtils.mkdir_p(resolver_folder)

          tlds.each do |tld|
            File.open(File.join(resolver_folder, tld), "w") do |f|
              f << resolver_file(port)
            end
          end

          env[:dns].ui.info "Created resolvers for tlds #{tlds}"

          @app.call(env)
        end

        private

        def resolver_file(port)
          contents = <<-FILE
# this file is generated by vagrant-dns
nameserver 127.0.0.1
port #{port}
FILE
        end
      end
    end
  end
end
